# Generated by Django 3.2 on 2021-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0005_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='sity',
            field=models.CharField(default='Qarshi', max_length=256),
        ),
    ]
