# Generated by Django 3.2 on 2021-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0006_education_sity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='sity',
            field=models.CharField(max_length=256),
        ),
    ]
